- name: Install Kerberos Client
  apt:
    name:
      - heimdal-clients
      - ntpdate
    state: present

- name: Configure Krb5
  copy:
    content: |
      [libdefaults]
          default_realm = {{ univention_krb5_realm }}
          kdc_timesync = 1
          ccache_type = 4
          forwardable = true
          proxiable = true
          default_tkt_enctypes = arcfour-hmac-md5 des-cbc-md5 des3-hmac-sha1 des-cbc-crc des-cbc-md4 des3-cbc-sha1 aes128-cts-hmac-sha1-96 aes256-cts-hmac-sha1-96
          permitted_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md4 des-cbc-md5 des3-cbc-sha1 arcfour-hmac-md5 aes128-cts-hmac-sha1-96 aes256-cts-hmac-sha1-96
          allow_weak_crypto=true

      [realms]
      {{ univention_krb5_realm }} = {
        kdc = {{ univention_master_node_ip }} {{ univention_master_node_fqdn }}
        admin_server = {{ univention_master_node_ip }} {{ univention_master_node_fqdn }}
        kpasswd_server = {{ univention_master_node_ip }} {{ univention_master_node_fqdn }}
    dest: /etc/krb5.conf
