- name: Create LDAP directory
  file:
    path: /etc/ldap
    state: directory

- name: Create LDAP Secret
  set_fact:
    ldap_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=25) }}"
  when:
    - univention_ldap_provisioning

- name: Configure LDAP Creatential
  copy:
    content: "{{ ldap_secret }}"
    dest: /etc/ldap.secret
    mode: 400

- name: Add Computer Account on UCS
  command: |
    udm computers/ubuntu create \
    --position "cn=computers,dc={{ univention_ldap_base | join(",dc=") }}" \
    --set name={{ inventory_hostname }} --set password="{{ ldap_secret }}" \
    --set operatingSystem="{{ ansible_distribution }}" \
    --set operatingSystemVersion="{{ ansible_distribution_major_version }}"
  when:
    - univention_ldap_provisioning
  delegate_to: "{{ univention_master_node_hostname }}"

- name: Create UCS Ca directory
  file:
    path: /etc/univention/ssl/ucsCA
    state: directory

- name: Download LDAP CA from Univention Server
  get_url:
    url: http://{{ univention_master_node_fqdn }}/ucs-root-ca.crt
    dest: /etc/univention/ssl/ucsCA/CAcert.pem

- name: Configure LDAP
  copy:
    content: |
      TLS_CACERT /etc/univention/ssl/ucsCA/CAcert.pem
      URI ldap://{{ univention_master_node_fqdn }}:7389
      BASE {{ univention_ldap_base }}
    dest: /etc/ldap/ldap.conf
