- name: Create LDAP directory
  file:
    path: /etc/ldap
    state: directory

- name: Create LDAP Secret
  set_fact:
    ldap_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=25) }}"
  when:
    - univention_ldap_provisioning

- name: Configure LDAP Creatential
  copy:
    content: "{{ ldap_secret }}"
    dest: /etc/ldap.secret
    mode: 400

- name: Add Computer Account on UCS if ldap_provisioning
  shell: |
    udm computers/linux create \
    --position "cn=computers,{{ univention_ldap_base }}" \
    --set name={{ inventory_hostname }} --set password="{{ ldap_secret }}" \
    --set operatingSystem="{{ ansible_distribution }}" \
    --set operatingSystemVersion="{{ ansible_distribution_major_version }}" \
    --set mac={{ ansible_default_ipv4.macaddress }} \
    --set ip={{ ansible_default_ipv4.address }} \
    --set dnsEntryZoneForward="zoneName={{ univention_host_dns_forward_zone }},cn=dns,{{ univention_ldap_base }} {{ ansible_default_ipv4.address }}" \
    --set dnsEntryZoneReverse="zoneName={{ univention_host_dns_reverse_zone }},cn=dns,{{ univention_ldap_base }} {{ ansible_default_ipv4.address }}"
  delegate_to: "{{ univention_master_node_hostname }}"
  when:
    - univention_ldap_provisioning

- name: Create UCS Ca directory
  file:
    path: /etc/univention/ssl/ucsCA
    state: directory

- name: Download LDAP CA from Univention Server
  file:
    src: /usr/local/share/ca-certificates/H2-UCS-ROOT-CA.crt
    dest: /etc/univention/ssl/ucsCA/CAcert.pem
    state: link

- name: Configure LDAP
  copy:
    content: |
      TLS_CACERT /etc/univention/ssl/ucsCA/CAcert.pem
      URI ldap://{{ univention_master_node_fqdn }}:7389
      BASE {{ univention_ldap_base }}
    dest: /etc/ldap/ldap.conf
