- name: Copy pam configuration
  copy:
    content: |
      Name: activate mkhomedir
      Default: yes
      Priority: 900
      Session-Type: Additional
      Session:
          required    pam_mkhomedir.so umask=0022 skel=/etc/skel
    dest: /usr/share/pam-configs/ucs_mkhomedir

- name: Run pam-update command
  command: pam-auth-update --force
  env:
    DEBIAN_FRONTEND: noninteractive

- name: create LightDM config dir
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory

- name: Remove users on Login Screen
  copy:
    content: |
      # Add a field for a user name, disable user selection at the login screen
      [SeatDefaults]
      greeter-show-manual-login=true
      greeter-hide-users=true
    dest: /etc/lightdm/lightdm.conf.d/99-show-manual-userlogin.conf