- name: Install SSSD Applications
  apt:
    name:
      - sssd
      - libnss-sss
      - libpam-sss
      - libsss-sudo
#      - auth-client-config

- name: Configure SSSD
  copy:
    content: |
      [sssd]
      config_file_version = 2
      reconnection_retries = 3
      sbus_timeout = 30
      services = nss, pam, sudo
      domains = {{ univention_krb5_realm }}

      [nss]
      reconnection_retries = 3

      [pam]
      reconnection_retries = 3

      [domain/{{ univention_krb5_realm }}]
      auth_provider = krb5
      krb5_realm = {{ univention_krb5_realm }}
      krb5_server = {{ univention_master_node_fqdn }}
      krb5_kpasswd = {{ univention_master_node_fqdn }}
      id_provider = ldap
      ldap_uri = ldap://{{ univention_master_node_fqdn }}:7389
      ldap_search_base = {{ univention_ldap_base }}
      ldap_tls_reqcert = never
      ldap_tls_cacert = /etc/univention/ssl/ucsCA/CAcert.pem
      cache_credentials = true
      enumerate = true
      ldap_default_bind_dn = cn={{ inventory_hostname }},cn=computers,{{ univention_ldap_base }}
      ldap_default_authtok_type = password
      ldap_default_authtok = {{ ldap_secret }}
    dest: /etc/sssd/sssd.conf 
    mode: 0600
    owner: root
    group: root

- name: Setup Auth-Client
  copy:
    content: |
      [sss]
      nss_passwd=   passwd:   compat sss
      nss_group=    group:    compat sss
      nss_shadow=   shadow:   compat
      nss_netgroup= netgroup: nis

      pam_auth=
              auth [success=3 default=ignore] pam_unix.so nullok_secure try_first_pass
              auth requisite pam_succeed_if.so uid >= 500 quiet
              auth [success=1 default=ignore] pam_sss.so use_first_pass
              auth requisite pam_deny.so
              auth required pam_permit.so

      pam_account=
              account required pam_unix.so
              account sufficient pam_localuser.so
              account sufficient pam_succeed_if.so uid < 500 quiet
              account [default=bad success=ok user_unknown=ignore] pam_sss.so
              account required pam_permit.so

      pam_password=
              password requisite pam_pwquality.so retry=3
              password sufficient pam_unix.so obscure sha512
              password sufficient pam_sss.so use_authtok
              password required pam_deny.so

      pam_session=
              session required pam_mkhomedir.so skel=/etc/skel/ umask=0077
              session optional pam_keyinit.so revoke
              session required pam_limits.so
              session [success=1 default=ignore] pam_sss.so
              session required pam_unix.so
    dest: /etc/auth-client-config/profile.d/sss
    mode: 600
  when:
    - false

- name: Run Auth-Client Command
  shell: DEBIAN_FRONTEND=noninteractive pam-auth-update --force
#  env:
#    DEBIAN_FRONTEND: noninteractive

- name: Restart SSSD
  service:
    name: sssd
    state: restarted